name: Python unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Unittests
        with:
          module: activcollabpysdk
        run: |
          python -m unittest discover
        # python -m unittest discover -s "tests/" -p "test_*.py"    
